modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "xu_component_lib"
version = "${version}"
displayName = "Xu Component Lib"
authors = "XuHaoNan"
description = '''
No Description For Now, This Project Now Is Under Development.
'''
#logoFile = ""

[[dependencies.xu_component_lib]]
modId = "neoforge"
type = "required"
versionRange = "[21,26)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xu_component_lib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "xu_component_lib.mixins.json"